spring:
  application:
    name: k-beauty

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

naver:
  shopping:
    base-url: https://openapi.naver.com
    client-id: ${NAVER_CLIENT_ID:}
    client-secret: ${NAVER_CLIENT_SECRET:}
